### ISSUE TITLE
Parallel citation syntax update

### ISSUE THREAD

**Issue by fbennett** [Juris-M/jm-style-tests#3]
@georged I have completed work on processor revisions for parallel citation support:

https://citeproc-js.readthedocs.io/en/latest/csl-m/index.html#parallel-citation-and-suppressing-repetition

The new syntax should be flexible enough to handle the various forms of parallel citation out there.

**Comment by georgd** [comment]
This is obsolete, isn’t it?

**Comment by fbennett** [comment]
Yes, it is. Docs need some attention.

**Comment by fbennett** [comment]
Docs have been updated.
